# Generated by Django 3.0.4 on 2020-03-20 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='first_name',
            new_name='mail_adress',
        ),
    ]
